openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    A simple API for managing a personal contact book.
     Allows users to perform CRUD (Create, Read, Update, Delete) operations
     on their contacts.
tags:
  - name: Contacts
    description: Operations related to managing contacts
  - name: Authentication
    description: Operations related to user authentication
servers:
  - url: http://localhost:3000
  - url:
paths:
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml

    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml

    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml

    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/current:
    get:
      $ref: ../swagger/paths/auth/current/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Contact:
      $ref: ../swagger/components/schemas/contactSchema.yaml

  responses:
    NotFound:
      $ref: ../swagger/components/responses/404-NotFound.yaml
    Unauthorized:
      $ref: ../swagger/components/responses/401-Unauthorized.yaml
